export interface DailyVerse {
  day: number;
  ref: string;
  bookId: string;
  bookName: string;
  chapter: number;
  verse: number;
  text: string;
  textNVI?: string;
  textKJV?: string;
  theme: string;
  reflection: string;
  challenge: string;
}

export const DAILY_VERSES: DailyVerse[] = [
  {
    day: 1,
    ref: 'Gênesis 1:1',
    bookId: 'GEN',
    bookName: 'Gênesis',
    chapter: 1,
    verse: 1,
    text: 'No princípio, criou Deus os céus e a terra.',
    textNVI: 'No princípio criou Deus os céus e a terra.',
    textKJV: 'In the beginning God created the heaven and the earth.',
    theme: 'Soberania e Criação',
    reflection: 'Este versículo estabelece a verdade fundamental de que o universo tem um Criador pessoal, transcendente e soberano. Toda a teologia bíblica repousa sobre este alicerce: Deus precede todas as coisas e é o autor de toda a existência.',
    challenge: 'Medite sobre a soberania de Deus. Como o fato de Ele ser o Criador de tudo traz paz e ordem para os seus dias?'
  },
  {
    day: 2,
    ref: 'João 1:1',
    bookId: 'JOH',
    bookName: 'João',
    chapter: 1,
    verse: 1,
    text: 'No princípio era o Verbo, e o Verbo estava com Deus, e o Verbo era Deus.',
    textNVI: 'No princípio era aquele que é a Palavra. Ele estava com Deus, e era Deus.',
    textKJV: 'In the beginning was the Word, and the Word was with God, and the Word was God.',
    theme: 'Cristologia e Eternidade',
    reflection: 'João faz eco ao Gênesis para demonstrar a eternidade de Jesus Cristo como o Verbo (Logos). Ele não é apenas uma criatura, mas o Deus eterno encarnado, a revelação perfeita do Pai e o agente ativo na criação.',
    challenge: 'Aprofunde-se na divindade de Cristo hoje. Lembre-se de que Jesus é a Palavra viva de Deus revelada a nós.'
  },
  {
    day: 3,
    ref: 'Romanos 8:28',
    bookId: 'ROM',
    bookName: 'Romanos',
    chapter: 8,
    verse: 28,
    text: 'Sabemos que todas as coisas cooperam para o bem daqueles que amam a Deus, daqueles que são chamados segundo o seu propósito.',
    textNVI: 'Sabemos que Deus age em todas as coisas para o bem daqueles que o amam, dos que foram chamados de acordo com o seu propósito.',
    textKJV: 'And we know that all things work together for good to them that love God, to them who are the called according to his purpose.',
    theme: 'Providência Divina',
    reflection: 'A providência de Deus não significa que não passaremos por sofrimentos, mas sim que Deus orquestra soberanamente até mesmo as dificuldades para a nossa santificação e para o cumprimento de Seus propósitos eternos.',
    challenge: 'Confie uma situação difícil de sua vida hoje ao controle providencial de Deus, crendo que Ele está agindo para o seu bem espiritual.'
  },
  {
    day: 4,
    ref: 'Efésios 2:8',
    bookId: 'EPH',
    bookName: 'Efésios',
    chapter: 2,
    verse: 8,
    text: 'Porque pela graça sois salvos, mediante a fé; e isto não vem de vós; é dom de Deus;',
    textNVI: 'Pois vocês são salvos pela graça, por meio da fé, e isto não vem de vocês, é dom de Deus;',
    textKJV: 'For by grace are ye saved through faith; and that not of yourselves: it is the gift of God:',
    theme: 'Soteriologia e Graça',
    reflection: 'A salvação é inteiramente um ato da graça soberana de Deus. Nem a nossa fé é mérito próprio; tudo é um presente imerecido oferecido pelo Pai por meio do sacrifício perfeito de Cristo na cruz.',
    challenge: 'Agradeça a Deus hoje pela salvação imerecida. Escreva uma breve oração expressando gratidão por Sua graça infinita.'
  },
  {
    day: 5,
    ref: 'Filipenses 4:13',
    bookId: 'PHI',
    bookName: 'Filipenses',
    chapter: 4,
    verse: 13,
    text: 'Tudo posso naquele que me fortalece.',
    textNVI: 'Tudo posso naquele que me fortalece.',
    textKJV: 'I can do all things through Christ which strengtheneth me.',
    theme: 'Contentamento e Força',
    reflection: 'Longe de ser uma fórmula para prosperidade material, Paulo escreveu isso em uma prisão romana. Refere-se à capacidade divina de estar contente e firme em qualquer circunstância — seja na fartura ou na escassez.',
    challenge: 'Pratique o contentamento hoje. Busque a força em Cristo para enfrentar o dia, independentemente das circunstâncias favoráveis ou difíceis.'
  },
  {
    day: 6,
    ref: 'Isaías 40:31',
    bookId: 'ISA',
    bookName: 'Isaías',
    chapter: 40,
    verse: 31,
    text: 'Mas os que esperam no Senhor renovam as suas forças, sobem com asas como águias, correm e não se cansam, caminham e não se fatigam.',
    textNVI: 'Mas aqueles que esperam no Senhor renovam as suas forças. Voam alto como águias; correm e não se cansam, caminham e não se fatigam.',
    textKJV: 'But they that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint.',
    theme: 'Confiança e Renovação',
    reflection: 'A nossa força humana é limitada e falha, mas o Senhor é inesgotável. Esperar ativamente no Senhor significa confiar na Sua fidelidade e tempo perfeito, recebendo dEle uma renovação sobrenatural para continuar.',
    challenge: 'Se você se sente espiritualmente cansado hoje, tire 10 minutos para silenciar o coração e pedir que o Espírito Santo renove as suas energias.'
  },
  {
    day: 7,
    ref: 'Salmo 23:1',
    bookId: 'PSA',
    bookName: 'Salmos',
    chapter: 23,
    verse: 1,
    text: 'O Senhor é o meu pastor; nada me faltará.',
    textNVI: 'O Senhor é o meu pastor; de nada terei falta.',
    textKJV: 'The LORD is my shepherd; I shall not want.',
    theme: 'Cuidado Pastoral Divino',
    reflection: 'Ao chamar Deus de seu Pastor, Davi reconhece o cuidado íntimo, a provisão material e espiritual, a proteção contra inimigos e a guia paciente que o Senhor exerce sobre cada uma de Suas ovelhas.',
    challenge: 'Descanse no pastoreio de Deus. Ore entregando suas preocupações financeiras e de saúde ao Pastor que cuida de você.'
  },
  {
    day: 8,
    ref: 'Provérbios 1:7',
    bookId: 'PRO',
    bookName: 'Provérbios',
    chapter: 1,
    verse: 7,
    text: 'O temor do Senhor é o princípio do saber, mas os loucos desprezam a sabedoria e o ensino.',
    textNVI: 'O temor do Senhor é o princípio do conhecimento, mas os insensatos desprezam a sabedoria e a disciplina.',
    textKJV: 'The fear of the LORD is the beginning of knowledge: but fools despise wisdom and instruction.',
    theme: 'Teologia da Sabedoria',
    reflection: 'O "temor do Senhor" não é um pavor servil, mas uma reverência profunda, admiração e submissão ao caráter de Deus. A verdadeira sabedoria acadêmica e de vida começa ao reconhecermos Deus como a fonte suprema da verdade.',
    challenge: 'Ao estudar ou tomar decisões hoje, peça primeiro sabedoria a Deus, reconhecendo a autoridade e reverência devidas a Ele.'
  },
  {
    day: 9,
    ref: 'João 14:6',
    bookId: 'JOH',
    bookName: 'João',
    chapter: 14,
    verse: 6,
    text: 'Respondeu-lhe Jesus: Eu sou o caminho, e a verdade, e a vida; ninguém vem ao Pai senão por mim.',
    textNVI: 'Disse-lhe Jesus: "Eu sou o caminho, a verdade e a vida. Ninguém vem ao Pai, a não ser por mim."',
    textKJV: 'Jesus saith unto him, I am the way, the truth, and the life: no man cometh unto the Father, but by me.',
    theme: 'Exclusividade de Cristo',
    reflection: 'Jesus não se apresenta apenas como um mestre que aponta uma direção, mas como a própria via de reconciliação com o Pai. Sua obra substitutiva e identidade divina O tornam o único mediador entre Deus e os homens.',
    challenge: 'Compartilhe hoje a esperança do Evangelho de Cristo com alguém, lembrando-se da singularidade salvífica do nosso Senhor.'
  },
  {
    day: 10,
    ref: 'Gálatas 2:20',
    bookId: 'GAL',
    bookName: 'Gálatas',
    chapter: 2,
    verse: 20,
    text: 'Estou crucificado com Cristo; logo, já não sou eu quem vive, mas Cristo vive em mim; e esse viver que, agora, tenho na carne, vivo pela fé no Filho de Deus, que me amou e a si mesmo se entregou por mim.',
    textNVI: 'Fui crucificado com Cristo. Assim, já não sou eu quem vive, mas Cristo vive em mim. A vida que agora vivo no corpo, vivo-a pela fé no Filho de Deus, que me amou e se entregou por mim.',
    textKJV: 'I am crucified with Christ: nevertheless I live; yet not I, but Christ liveth in me: and the life which I now live in the flesh I live by the faith of the Son of God, who loved me, and gave himself for himself.',
    theme: 'União com Cristo',
    reflection: 'A vida cristã autêntica é caracterizada pela identificação com a morte e ressurreição de Cristo. Nossa antiga natureza egoísta foi sepultada, e nossa nova identidade é alimentada pela fé diária na soberania amorosa do Filho de Deus.',
    challenge: 'Renuncie a uma atitude de orgulho ou egoísmo hoje, deixando que Cristo reine e guie as suas respostas práticas.'
  },
  {
    day: 11,
    ref: 'Hebreus 11:1',
    bookId: 'HEB',
    bookName: 'Hebreus',
    chapter: 11,
    verse: 1,
    text: 'Ora, a fé é a certeza de coisas que se esperam, a convicção de fatos que se não veem.',
    textNVI: 'Ora, a fé é a certeza daquilo que esperamos e a prova das coisas que não vemos.',
    textKJV: 'Now faith is the substance of things hoped for, the evidence of things not seen.',
    theme: 'Definição de Fé',
    reflection: 'A fé bíblica não é uma crença cega ou mera emoção, mas uma convicção fundamentada no caráter e nas promessas inabaláveis de Deus. Ela nos dá segurança absoluta sobre o futuro eterno prometido pelas Escrituras.',
    challenge: 'Identifique uma área onde sua fé tem vacilado e escreva uma promessa bíblica que fortaleça sua confiança no Deus fiel.'
  },
  {
    day: 12,
    ref: 'Mateus 6:33',
    bookId: 'MAT',
    bookName: 'Mateus',
    chapter: 6,
    verse: 33,
    text: 'Buscai, pois, em primeiro lugar, o seu reino e a sua justiça, e todas estas coisas vos serão acrescentadas.',
    textNVI: 'Busquem, pois, em primeiro lugar o Reino de Deus e a sua justiça, e todas essas coisas lhes serão acrescentadas.',
    textKJV: 'But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you.',
    theme: 'Prioridade do Reino',
    reflection: 'Contra a ansiedade diária pela sobrevivência material, Jesus nos convida a reordenar nossos corações. Colocar o Reino de Deus e a Sua retidão moral em primeiro plano nos liberta das preocupações, pois o Pai conhece nossas necessidades.',
    challenge: 'Faça uma lista das suas prioridades de tempo hoje. Como você pode dedicar o início do seu dia para buscar o Reino de Deus de forma prática?'
  },
  {
    day: 13,
    ref: '2 Timóteo 3:16',
    bookId: '2TIM',
    bookName: '2 Timóteo',
    chapter: 3,
    verse: 16,
    text: 'Toda a Escritura é inspirada por Deus e útil para o ensino, para a repreensão, para a correção, para a educação na justiça,',
    textNVI: 'Toda a Escritura é inspirada por Deus e útil para o ensino, para a repreensão, para a correção e para a instrução na justiça,',
    textKJV: 'All scripture is given by inspiration of God, and is profitable for doctrine, for reproof, for correction, for instruction in righteousness:',
    theme: 'Inerrância e Suficiência Bíblica',
    reflection: 'A palavra "inspirada" (Theopneustos) significa literalmente "soprada por Deus". Isso garante que a Escritura carrega autoridade divina intrínseca e é perfeitamente suficiente para nos moldar intelectual e espiritualmente.',
    challenge: 'Pratique a hermenêutica acadêmica e a leitura humilde hoje. Use o leitor bíblico do aplicativo para estudar um capítulo complexo.'
  },
  {
    day: 14,
    ref: 'Romanos 12:1',
    bookId: 'ROM',
    bookName: 'Romanos',
    chapter: 12,
    verse: 1,
    text: 'Rogo-vos, pois, irmãos, pelas misericórdias de Deus, que apresenteis o vosso corpo por sacrifício vivo, santo e agradável a Deus, que é o vosso culto racional.',
    textNVI: 'Portanto, irmãos, rogo-lhes pelas misericórdias de Deus que se ofereçam em sacrifício vivo, santo e agradável a Deus; este é o culto racional de vocês.',
    textKJV: 'I beseech you therefore, brethren, by the mercies of God, that ye present your bodies a living sacrifice, holy, acceptable unto God, which is your reasonable service.',
    theme: 'Consagração e Adoração',
    reflection: 'A resposta adequada às profundas verdades da salvação expostas por Paulo não é apenas um assentimento intelectual, mas a consagração diária de toda a nossa vida (corpo, mente e escolhas) como um ato de adoração lógico e consciente.',
    challenge: 'O que significa sacrificar suas vontades hoje? Tome uma decisão prática que honre a Deus, mesmo que exija renúncia.'
  },
  {
    day: 15,
    ref: 'Colossenses 1:16',
    bookId: 'COL',
    bookName: 'Colossenses',
    chapter: 1,
    verse: 16,
    text: 'Pois, nele, foram criadas todas as coisas, nos céus e sobre a terra, as visíveis e as invisíveis... Tudo foi criado por meio dele e para ele.',
    textNVI: 'Pois nele foram criadas todas as coisas nos céus e na terra, as visíveis e as invisíveis... Tudo foi criado por meio dele e para ele.',
    textKJV: 'For by him were all things created, that are in heaven, and that are in earth, visible and invisible... all things were created by him, and for him:',
    theme: 'Supremacia de Cristo',
    reflection: 'Cristo não é meramente um espectador da história. Ele é o Arquiteto Cósmico, o Sustentador de todas as coisas visíveis e invisíveis, e o objetivo final de toda a história humana. Nossa existência encontra seu verdadeiro propósito nEle.',
    challenge: 'Lembre-se hoje de que você foi criado "para Cristo". Como isso altera a perspectiva sobre seus relacionamentos e trabalho?'
  },
  {
    day: 16,
    ref: 'Salmo 119:105',
    bookId: 'PSA',
    bookName: 'Salmos',
    chapter: 119,
    verse: 105,
    text: 'Lâmpada para os meus pés é a tua palavra e luz, para os meus caminhos.',
    textNVI: 'A tua palavra é lâmpada que ilumina os meus passos e luz que clareia o meu caminho.',
    textKJV: 'Thy word is a lamp unto my feet, and a light unto my path.',
    theme: 'Guia da Revelação',
    reflection: 'Em um mundo mergulhado na escuridão ética, moral e teológica, a Palavra escrita de Deus funciona como uma chama focada para as escolhas cotidianas (lâmpada para os pés) e como uma luz ampla para os rumos gerais da vida (luz para o caminho).',
    challenge: 'Ao enfrentar uma decisão difícil hoje, consulte as Escrituras e peça orientação com base nos princípios bíblicos claros.'
  },
  {
    day: 17,
    ref: 'Tiago 1:5',
    bookId: 'JAS',
    bookName: 'Tiago',
    chapter: 1,
    verse: 5,
    text: 'Se algum de vós tem falta de sabedoria, peça-a a Deus, que a todos dá liberalmente e nada lhes impropera; e ser-lhe-á concedida.',
    textNVI: 'Se algum de vocês tem falta de sabedoria, peça-a a Deus, que a todos dá livremente, de boa vontade; e lhe será concedida.',
    textKJV: 'If any of you lack wisdom, let him ask of God, that giveth to all men liberally, and upbraideth not; and it shall be given him.',
    theme: 'Sabedoria em Oração',
    reflection: 'Diferente do conhecimento secular, a sabedoria bíblica é a habilidade divina de viver de forma justa e de tomar decisões piedosas em meio às provações. Deus se alegra em concedê-la generosamente àqueles que oram com fé expectante.',
    challenge: 'Apresente uma questão complexa que exige discernimento hoje em oração silenciosa, pedindo que Deus guie sua mente.'
  },
  {
    day: 18,
    ref: 'Romanos 5:1',
    bookId: 'ROM',
    bookName: 'Romanos',
    chapter: 5,
    verse: 1,
    text: 'Justificados, pois, mediante a fé, temos paz com Deus por meio de nosso Senhor Jesus Cristo;',
    textNVI: 'Tendo sido, pois, justificados pela fé, temos paz com Deus, por meio de nosso Senhor Jesus Cristo,',
    textKJV: 'Therefore being justified by faith, we have peace with God through our Lord Jesus Christ:',
    theme: 'Justificação e Paz',
    reflection: 'A justificação é o veredito legal de Deus declarando o pecador "justo" com base na justiça imputada de Cristo. O resultado imediato desse ato judicial não é apenas um sentimento, mas o estado objetivo de paz e amizade eterna com o Criador.',
    challenge: 'Silencie a culpa interna hoje descansando no veredito de "Justificado" que Cristo comprou para você.'
  },
  {
    day: 19,
    ref: '1 João 4:8',
    bookId: '1JOH',
    bookName: '1 João',
    chapter: 4,
    verse: 8,
    text: 'Aquele que não ama não conhece a Deus, pois Deus é amor.',
    textNVI: 'Quem não ama não conhece a Deus, porque Deus é amor.',
    textKJV: 'He that loveth not knoweth not God; for God is love.',
    theme: 'O Caráter de Deus',
    reflection: 'O amor não é apenas um dos atributos de Deus; é a Sua própria essência comunicada a nós através de Suas ações salvíficas. Portanto, qualquer teologia ou conhecimento bíblico que não resulte em amor ativo pelo próximo é falso e vazio.',
    challenge: 'Identifique uma pessoa com quem você tem dificuldades e pratique um ato deliberado de generosidade ou encorajamento hoje.'
  },
  {
    day: 20,
    ref: 'Salmo 46:1',
    bookId: 'PSA',
    bookName: 'Salmos',
    chapter: 46,
    verse: 1,
    text: 'Deus é o nosso refúgio e fortaleza, socorro bem presente nas tribulações.',
    textNVI: 'Deus é o nosso refúgio e a nossa fortaleza, auxílio sempre presente na adversidade.',
    textKJV: 'God is our refuge and strength, a very present help in trouble.',
    theme: 'Segurança e Soberania',
    reflection: 'Mesmo que a terra se mude e os montes se abalem, os crentes têm segurança inabalável. Deus não é apenas um auxílio distante, mas um socorro "bem presente" no calor da aflição cotidiana.',
    challenge: 'Escreva em uma folha ou nota no app o seu maior medo atual e declare sob ele a verdade de que Deus é a sua fortaleza inabalável.'
  },
  {
    day: 21,
    ref: 'Apocalipse 21:4',
    bookId: 'REV',
    bookName: 'Apocalipse',
    chapter: 21,
    verse: 4,
    text: 'E lhes enxugará dos olhos toda lágrima, e a morte já não existirá, já não haverá luto, nem pranto, nem dor, porque as primeiras coisas passaram.',
    textNVI: 'Ele enxugará dos seus olhos toda lágrima. Não haverá mais morte, nem tristeza, nem choro, nem dor, pois a antiga ordem de coisas já passou.',
    textKJV: 'And God shall wipe away all tears from their eyes; and there shall be no more death, neither sorrow, nor crying, neither shall there be any more pain: for the former things are passed away.',
    theme: 'Escatologia e Nova Criação',
    reflection: 'O destino final da história humana não é o aniquilamento ou uma existência etérea distante, mas a ressurreição física e a restauração de toda a criação. Deus habitará com Seu povo, eliminando permanentemente todo sofrimento e a própria morte.',
    challenge: 'Enfrente as tristezas temporárias de hoje com o olhar fixado na glória escatológica que nos aguarda.'
  },
  {
    day: 22,
    ref: '1 Coríntios 15:3',
    bookId: '1COR',
    bookName: '1 Coríntios',
    chapter: 15,
    verse: 3,
    text: 'Antes de tudo, vos entreguei o que também recebi: que Cristo morreu pelos nossos pecados, segundo as Escrituras,',
    textNVI: 'Pois o que primeiramente lhes transmiti foi o que recebi: que Cristo morreu pelos nossos pecados, segundo as Escrituras,',
    textKJV: 'For I delivered unto you first of all that which I also received, how that Christ died for our sins according to the scriptures;',
    theme: 'O Evangelho Central',
    reflection: 'Paulo define o coração do Evangelho histórico: a morte expiatória e vicária de Cristo, preanunciada nas profecias do Antigo Testamento. Toda a nossa teologia deve girar e se fundamentar nessa verdade objetiva e histórica.',
    challenge: 'Explique em duas ou três frases simples para si mesmo o que é o Evangelho, testando sua clareza sobre a graça.'
  },
  {
    day: 23,
    ref: 'Sofonias 3:17',
    bookId: 'ZEP',
    bookName: 'Sofonias',
    chapter: 3,
    verse: 17,
    text: 'O Senhor, teu Deus, está no meio de ti, poderoso para salvar-te; ele se deleitará em ti com alegria; renovar-te-á no seu amor, regozijar-se-á em ti com júbilo.',
    textNVI: 'O Senhor, o seu Deus, está em seu meio, poderoso para salvar. Ele se alegrará em você com júbilo, no seu amor o renovará, ele se regozijará em você com brados de alegria.',
    textKJV: 'The LORD thy God in the midst of thee is mighty; he will save, he will rejoice over thee with joy; he will rest in his love, he will joy over thee with singing.',
    theme: 'Amor Redentor de Deus',
    reflection: 'Muitas vezes imaginamos Deus como um juiz severo e distante, mas Sofonias O retrata como um guerreiro vitorioso que se deleita com alegria amorosa sobre o Seu povo remido, cantando canções de júbilo sobre nós.',
    challenge: 'Medite no fato de que Deus se alegra em você por causa de Cristo. Deixe esse amor perfeito acalmar a sua alma hoje.'
  },
  {
    day: 24,
    ref: 'Romanos 3:23',
    bookId: 'ROM',
    bookName: 'Romanos',
    chapter: 3,
    verse: 23,
    text: 'Pois todos pecaram e carecem da glória de Deus, sendo justificados gratuitamente, por sua graça, mediante a redenção que há em Cristo Jesus;',
    textNVI: 'pois todos pecaram e estão destituídos da glória de Deus, sendo justificados gratuitamente por sua graça, por meio da redenção que há em Cristo Jesus.',
    textKJV: 'For all have sinned, and come short of the glory of God; Being justified freely by his grace through the redemption that is in Christ Jesus:',
    theme: 'Hamartologia e Redenção',
    reflection: 'O diagnóstico bíblico da humanidade é universal: todos pecaram, errando o alvo da santidade divina. Contudo, a boa notícia da graça é que o próprio Deus providenciou a redenção necessária de forma inteiramente gratuita para nós.',
    challenge: 'Confesse humildemente os seus pecados de hoje e corra imediatamente para os braços da graça justificadora em Cristo.'
  },
  {
    day: 25,
    ref: 'Deuteronômio 6:5',
    bookId: 'DEU',
    bookName: 'Deuteronômio',
    chapter: 6,
    verse: 5,
    text: 'Amarás, pois, o Senhor, teu Deus, de todo o teu coração, de toda a tua alma e de toda a tua força.',
    textNVI: 'Ame o Senhor, o seu Deus, de todo o seu coração, de toda a sua alma e de todas as suas forças.',
    textKJV: 'And thou shalt love the LORD thy God with all thine heart, and with all thy soul, and with all thy might.',
    theme: 'O Grande Mandamento',
    reflection: 'A teologia da Shemá israelita aponta para uma consagração que engloba a totalidade da nossa existência. Amar a Deus não é apenas sentimentos, mas a submissão dos nossos pensamentos (coração), desejos (alma) e recursos diários (forças).',
    challenge: 'Tome uma decisão prática hoje demonstrando que seu amor por Deus é superior aos seus desejos pessoais.'
  },
  {
    day: 26,
    ref: 'Hebreus 4:12',
    bookId: 'HEB',
    bookName: 'Hebreus',
    chapter: 4,
    verse: 12,
    text: 'Porque a palavra de Deus é viva, e eficaz, e mais cortante do que qualquer espada de dois gumes... e é apta para discernir os pensamentos e intenções do coração.',
    textNVI: 'Pois a palavra de Deus é viva e eficaz, e mais afiada que qualquer espada de dois gumes... ela julga os pensamentos e as intenções do coração.',
    textKJV: 'For the word of God is quick, and powerful, and sharper than any twoedged sword... and is a discerner of the thoughts and intents of the heart.',
    theme: 'O Poder Penetrante da Palavra',
    reflection: 'A Escritura não é uma literatura estática, mas um instrumento dinâmico pelo qual o Espírito de Deus penetra profundamente em nossa psique, expondo nossas falsas motivações e trazendo real discernimento espiritual.',
    challenge: 'Abra seu coração sem reservas para a leitura bíblica de hoje, permitindo que o texto confronte e examine suas verdadeiras intenções.'
  },
  {
    day: 27,
    ref: 'Salmo 19:1',
    bookId: 'PSA',
    bookName: 'Salmos',
    chapter: 19,
    verse: 1,
    text: 'Os céus proclamam a glória de Deus, e o firmamento anuncia as obras das suas mãos.',
    textNVI: 'Os céus declaram a glória de Deus; o firmamento proclama a obra das suas mãos.',
    textKJV: 'The heavens declare the glory of God; and the firmament sheweth his handywork.',
    theme: 'Revelação Geral',
    reflection: 'O mundo físico ao nosso redor é um púlpito constante que revela a inteligência, o poder e a beleza majestosa do Criador. A criação inteira funciona como um testemunho mudo e universal sobre a existência e grandeza de Deus.',
    challenge: 'Hoje, ao olhar para a natureza, o céu ou mesmo o funcionamento de um organismo, expresse louvores ao Grande Arquiteto.'
  },
  {
    day: 28,
    ref: 'Mateus 28:19',
    bookId: 'MAT',
    bookName: 'Mateus',
    chapter: 28,
    verse: 19,
    text: 'Ide, portanto, fazei discípulos de todas as nações, batizando-os em nome do Pai, e do Filho, e do Espírito Santo;',
    textNVI: 'Portanto, vão e façam discípulos de todas as nações, batizando-os em nome do Pai e do Filho e do Espírito Santo,',
    textKJV: 'Go ye therefore, and teach all nations, baptizing them in the name of the Father, and of the Son, and of the Holy Ghost:',
    theme: 'Missiologia e Discipulado',
    reflection: 'A Grande Comissão dada pelo Senhor Jesus é o mandato imperativo da Igreja. O objetivo principal das missões não é apenas pregar, mas formar seguidores maduros e enraizados na verdade Trinitária do Pai, Filho e Espírito Santo.',
    challenge: 'Como você pode exercer influência de discipulado na vida de alguém hoje? Ore e se coloque à disposição para ensinar ou incentivar um irmão.'
  },
  {
    day: 29,
    ref: 'Miqueias 6:8',
    bookId: 'MIC',
    bookName: 'Miqueias',
    chapter: 6,
    verse: 8,
    text: 'Ele te declarou, ó homem, o que é bom e o que é que o Senhor pede de ti: que confesses a justiça, e ames a misericórdia, e andes humildemente com o teu Deus.',
    textNVI: 'Ele mostrou a você, ó homem, o que é bom e o que o Senhor exige: Pratique a justiça, ame a fidelidade e ande humildemente com o seu Deus.',
    textKJV: 'He hath shewed thee, O man, what is good; and what doth the LORD require of thee, but to do justly, and to love mercy, and to walk humbly with thy God?',
    theme: 'Justiça, Misericórdia e Humildade',
    reflection: 'Deus rejeita os rituais vazios que não se traduzem em retidão social e pessoal. O que Ele realmente requer de Seus filhos são atos de justiça objetiva, um coração misericordioso e pronto para perdoar, e uma caminhada humilde de dependência.',
    challenge: 'Avalie suas ações hoje: você tem agido com justiça no trabalho e praticado misericórdia sincera em seus relacionamentos?'
  },
  {
    day: 30,
    ref: 'João 16:33',
    bookId: 'JOH',
    bookName: 'João',
    chapter: 16,
    verse: 33,
    text: 'Tenho-vos dito estas coisas para que em mim tenhais paz. No mundo tereis aflições; mas tende bom ânimo; eu venci o mundo.',
    textNVI: 'Eu lhes disse essas coisas para que em mim vocês tenham paz. No mundo vocês terão aflições; contudo, tenham bom ânimo! Eu venci o mundo.',
    textKJV: 'These things I have spoken unto you, that in me ye might have peace. In the world ye shall have tribulation: but be of good cheer; I have overcome the world.',
    theme: 'Paz Teológica em Cristo',
    reflection: 'Jesus não promete uma vida sem lutas, mas garante que a vitória final já foi conquistada por Ele na cruz e na ressurreição. Nossa paz espiritual está ancorada na realidade inabalável de Sua vitória absoluta sobre o pecado e o mundo.',
    challenge: 'Encare os desafios e estresses do dia de hoje sabendo que a vitória final já está assegurada por Jesus.'
  },
  {
    day: 31,
    ref: 'Josué 1:9',
    bookId: 'JOS',
    bookName: 'Josué',
    chapter: 1,
    verse: 9,
    text: 'Não to mandei eu? Sê forte e corajoso; não temas, nem te espantes, porque o Senhor, teu Deus, é contigo, por onde quer que andares.',
    textNVI: 'Não fui eu que lhe ordenei? Seja forte e corajoso! Não se apavore, nem desanime, pois o Senhor, o seu Deus, estará com você por onde você andar.',
    textKJV: 'Have not I commanded thee? Be strong and of a good courage; be not afraid, neither be thou dismayed: for the LORD thy God is with thee whithersoever thou goest.',
    theme: 'Coragem Divina e Presença',
    reflection: 'A coragem de Josué não repousava em sua habilidade militar própria, mas no mandato soberano e na promessa de presença constante do Senhor. A presença ativa de Deus ao nosso lado é o maior antídoto contra todo medo e ansiedade.',
    challenge: 'Diga ao seu coração: "Deus está comigo hoje e guiará meus passos". Avance com coragem na tarefa que parece difícil.'
  }
];

export function getDailyVerse(day?: number): DailyVerse {
  const selectedDay = day || new Date().getDate();
  // Find the verse by day, or fallback to the first one
  const verse = DAILY_VERSES.find(v => v.day === selectedDay) || DAILY_VERSES[0];
  return verse;
}
