import { ChatMessage } from '../types';
import { normalizeReferencesInText } from '../services/aiService';

export interface ApiError {
  code: string;
  error: string;
  message: string;
}

/**
 * Sends messages history to the Gemini AI Assistant backend API.
 * Maps server-side error responses to structured errors.
 * 
 * @param messages The complete conversation history
 * @param option The theological study mode ('exegese' | 'hermeneutica' | 'devocional' | 'mapa_mental')
 * @returns Promise<string> The text generated by the AI
 */
export async function sendChatMessage(
  messages: ChatMessage[],
  option: 'exegese' | 'hermeneutica' | 'devocional' | 'mapa_mental'
): Promise<string> {
  try {
    const normalizedMessages = messages.map(msg => ({
      ...msg,
      content: normalizeReferencesInText(msg.content)
    }));

    const response = await fetch('/api/chat', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        messages: normalizedMessages,
        option,
      }),
    });

    let data: any = {};
    const contentType = response.headers.get('content-type');
    const isJson = contentType && contentType.includes('application/json');

    if (isJson) {
      try {
        data = await response.json();
      } catch (parseErr: any) {
        data = { error: 'Erro de Parse JSON', message: 'Falha ao decodificar a resposta JSON do servidor: ' + parseErr.message };
      }
    } else {
      const rawText = await response.text();
      // Keep it short and readable in case of giant HTML
      const previewText = rawText.length > 200 ? rawText.slice(0, 200) + '...' : rawText;
      data = {
        error: `Resposta não-JSON (Status ${response.status})`,
        message: previewText || 'O servidor retornou uma resposta vazia ou HTML.'
      };
    }

    if (!response.ok) {
      const apiError: ApiError = {
        code: data.code || 'HTTP_ERROR_' + response.status,
        error: data.error || `Erro do Servidor (${response.status})`,
        message: data.message || `Ocorreu um erro no servidor (Status ${response.status}). Por favor, tente novamente.`
      };
      throw new Error(JSON.stringify(apiError));
    }

    if (!data.text) {
      throw new Error(JSON.stringify({
        code: 'EMPTY_RESPONSE',
        error: 'Resposta vazia da IA.',
        message: 'O modelo do Gemini retornou uma resposta em branco. Por favor, tente reformular sua consulta.'
      }));
    }

    return data.text;
  } catch (err: any) {
    // If it's already a structured JSON string we threw above, rethrow it
    let isStructured = false;
    try {
      const parsed = JSON.parse(err.message);
      if (parsed && parsed.code && parsed.error && parsed.message) {
        isStructured = true;
      }
    } catch {
      // Ignored
    }

    if (isStructured) {
      throw err;
    }

    // Default network failure / server offline mapping with original error message for maximum transparency
    const networkError: ApiError = {
      code: 'CONNECTION_FAILED',
      error: 'Falha na conexão.',
      message: err.message || 'Não foi possível conectar ao servidor do Assistente Teológico. Verifique sua conexão ou tente novamente mais tarde.'
    };
    throw new Error(JSON.stringify(networkError));
  }
}

/**
 * Request the backend to generate a 30-day theological study plan using Gemini.
 * 
 * @param theme The theological topic/theme
 * @returns Promise<any> The generated plan object
 */
export async function generateTheologicalPlan(theme: string): Promise<any> {
  try {
    const normalizedTheme = normalizeReferencesInText(theme);
    const response = await fetch('/api/generate-plan', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ theme: normalizedTheme }),
    });

    if (!response.ok) {
      throw new Error(`Erro de resposta: Código ${response.status}`);
    }

    return await response.json();
  } catch (err: any) {
    console.error('Erro de conexão ao gerar plano:', err);
    throw err;
  }
}
