import { ChatMessage } from '../types';

export interface ApiError {
  code: string;
  error: string;
  message: string;
}

/**
 * Sends messages history to the Gemini AI Assistant backend API.
 * Maps server-side error responses to structured errors.
 * 
 * @param messages The complete conversation history
 * @param option The theological study mode ('exegese' | 'hermeneutica' | 'devocional' | 'mapa_mental')
 * @returns Promise<string> The text generated by the AI
 */
export async function sendChatMessage(
  messages: ChatMessage[],
  option: 'exegese' | 'hermeneutica' | 'devocional' | 'mapa_mental'
): Promise<string> {
  try {
    const response = await fetch('/api/chat', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        messages,
        option,
      }),
    });

    const data = await response.json();

    if (!response.ok) {
      // Create a structured error using server response or defaults
      const apiError: ApiError = {
        code: data.code || 'HTTP_ERROR_' + response.status,
        error: data.error || 'Erro na requisição da API.',
        message: data.message || `Ocorreu um erro no servidor (Status ${response.status}). Por favor, tente novamente.`
      };
      throw new Error(JSON.stringify(apiError));
    }

    if (!data.text) {
      throw new Error(JSON.stringify({
        code: 'EMPTY_RESPONSE',
        error: 'Resposta vazia da IA.',
        message: 'O modelo do Gemini retornou uma resposta em branco. Por favor, tente reformular sua consulta.'
      }));
    }

    return data.text;
  } catch (err: any) {
    // If it's already a structured JSON string we threw above, rethrow it
    try {
      const parsed = JSON.parse(err.message);
      if (parsed && parsed.code && parsed.error && parsed.message) {
        throw err;
      }
    } catch {
      // Ignored: Not a structured JSON string, handle as connection/network error
    }

    // Default network failure / server offline mapping
    const networkError: ApiError = {
      code: 'CONNECTION_FAILED',
      error: 'Falha na conexão.',
      message: 'Não foi possível conectar ao servidor do Assistente Teológico. Verifique sua conexão ou tente novamente mais tarde.'
    };
    throw new Error(JSON.stringify(networkError));
  }
}
